### ISSUE TITLE
Add CSS for index layout & design

### ISSUE THREAD

**Issue by sscovil** [sscovil/something-awesome#8]
To give the markup we added in #7 the correct layout and make it look much nicer, we need to add some CSS rules to [style.css](https://github.com/sscovil/something-awesome/blob/master/src/public/style.css).

For this, we're going to:

- [x] import a couple of Google fonts ([Open Sans](https://fonts.google.com/specimen/Open+Sans) and [Merriweather](https://fonts.google.com/specimen/Merriweather)) 
- [x] apply Open Sans font style for all headings `h1` through `h6`
- [x] apply Merriweather font style for all other text
- [x] constrain the width of the header, nav/main section, and footer elements to `980px`
- [x] ensure the nav sidebar is 1/3 the width of the header and footer
- [x] ensure the main section is 2/3 the width of the header and footer
- [x] ensure the nav sidebar is aligned to the left of the main section
- [x] give both the main and nav sections `20px` padding
- [x] add colors: text: `#4a4a4a` links: `#00d1b2` headings & hover links: `#363636`
- [x] remove bullets, margins and padding from link list in nav section

To import the Google fonts, you can use the following CSS:

``` css
@import url('https://fonts.googleapis.com/css?family=Merriweather|Open+Sans');

h1, h2, h3, h4, h5, h6 {
  font-family: 'Open Sans', sans-serif;
}

body {
  font-family: 'Merriweather', serif;
}
```
